inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'run-foodcritic'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/MethodLength:
  Max: 30
