language: generic
sudo: true
dist: trusty

install:
- wget https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip
- sudo unzip packer_0.10.1_linux_amd64.zip -d /usr/local/packer
- export PATH=$PATH:/usr/local/packer

script:
- export YML=$(git log --name-only --oneline -n 1 | grep .yml) && if [[ ! -z $YML ]]; then echo "make $YML"; else exit 0; fi
- make min.yml
