language: generic
sudo: true
dist: trusty
install:
- wget https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip
- sudo unzip packer_0.10.1_linux_amd64.zip -d /usr/local/packer
- export PATH=$PATH:/usr/local/packer
before_install:
- openssl aes-256-cbc -K $encrypted_aba34ae14add_key -iv $encrypted_aba34ae14add_iv
  -in gce-packer-acct.json.enc -out gce-packer-acct.json -d
- openssl aes-256-cbc -K $encrypted_aba34ae14add_key -iv $encrypted_aba34ae14add_iv
  -in .env.enc -out .env -d
before_script:
- source .env
script:
- packer build -only=googlecompute <(bin/yml2json < worker.yml)
