language: generic

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:$PATH"

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

script:
- make
- git diff --exit-code
- git diff --cached --exit-code
- ./runtests
