language: generic
sudo: true
dist: trusty
install:
- wget https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip
- sudo unzip packer_0.10.1_linux_amd64.zip -d /usr/local/packer
- export PATH=$PATH:/usr/local/packer
before_install:
- source .env

script:
- packer build -only=googlecompute <(bin/yml2json < worker.yml)
