language: generic
sudo: true
dist: trusty
install:
- wget https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip
- sudo unzip packer_0.10.1_linux_amd64.zip -d /usr/local/packer
- export PATH=$PATH:/usr/local/packer
before_install:
- openssl aes-256-cbc -K $encrypted_aba34ae14add_key -iv $encrypted_aba34ae14add_iv
  -in min.yml.enc -out min.yml -d
script: 
- cat min.yml.enc
